### ISSUE TITLE
Please remove the front-end

### ISSUE THREAD

**Issue by ines** [uhh-lt/targer#40]
The JavaScript code you're using here, [`displacy-ent`](https://github.com/explosion/displacy-ent) is open-source and MIT-licensed, so that's no problem. Although, I would have appreciated attribution beyond a note like "implemented with displaCy" somewhere [hidden](https://github.com/uhh-lt/targer/blob/master/frontend/README.md) in the repo. Your poster cites "user-friendly web interface" as one of the main features, so I think it would have been only fair to cite the original author of it (me).

Aside from that, the UI you use was directly copied from our website, [explosion.ai](https://explosion.ai) ([see here](https://explosion.ai/demos/displacy-ent)). That front-end code is **not open-source** and not released under any license. It's **not even public on GitHub**.  It was copied by just saving the compiled HTML and [full stylesheet of the site](https://github.com/uhh-lt/targer/blob/master/frontend/static/css/style.css) ([see here](https://explosion.ai/assets/css/style.css) for comparison). This means that it can't just be used and published as part of this open-source demo.

Another very significant problem is this line:

https://github.com/uhh-lt/targer/blob/1a977fcdc96ba0e3441031699728d141aaac56cf/frontend/templates/displacy.html#L186

When you copied the entire page, you did remove our logo and copyright notice. However, you forgot to remove our fonts counter, which pings [MyFonts](https://www.myfonts.com/). We're paying for the fonts we're using and it's rated by page views. With all the ACL people visiting your demo now, this can potentially mean that we have to pay more money. That sucks and is pretty unfair.

**Comment by alexanderpanchenko** [comment]
Hello Ines,

I am really sorry about it. We will do all the attributions to your library. The copy-paste was done by a student (I thought that the it was part of the github repository - sorry if it was not). We will remove non-free parts from the demo of course!

Let me know if you have any specific ways of acknowledgement you want to see.

**Comment by honnibal** [comment]
Could you comment on the decision to not attribute the frontend in your paper, poster, demo website or the repository readme?

**Comment by alexanderpanchenko** [comment]
It was a terrible overlooked thing. We will fix it where possible! We were focusing on the backend mostly training all of these models and performing web scale indexing... the front end was an important part but we just decided to take something decent from open source as none of us is a specialist in the front end. Unfortunately the Bachelor student working on front end presumably used not only github MIT repository but also done this idiotic copy-paste from your web site (and as both look very similar none of us spotted the issue). We will do our best ASAP to make sure only MIT code is used.

I am really apologize for this!

**Comment by alexteua** [comment]
Hello Ines and Matthew, 

We are sorry for these issues and will surely do the changes. 
First of all, the font counter is removed from the demo. Other steps will be done asap.

**Comment by alexanderpanchenko** [comment]
Now I am trying to understand how it happened that the html ended up in this project: I suppose that the hyperlink in the repository confused our student: it points to your web site and probably he supposed that is is the same thing as the code in the repository, while it was not. 

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1456830/62079634-664d1900-b24f-11e9-97a0-2d3185d739e5.png">

This is by no means an excuse - I just trying to figure out how it happened. Again really sorry for this. We will remove all non-MIT parts but just we need some time to fix it.

**Comment by alexanderpanchenko** [comment]
@ines I've updated readme indicating a more explicit reference to the repository which was used. 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1456830/62080394-da3bf100-b250-11e9-89de-6f2bcf0ab25f.png">

Please let me know if this is ok. 

We will reworking the front-end: I really should have recognized it earlier that the URL on the github lead to propriatery page (and some elements are not contained in the repository).

**Comment by ines** [comment]
Hi @alexanderpanchenko & @alexteua. Thanks for your replies – I'm glad we're on the same page about this 🙂

I have to say, I'm still a bit confused about this part:

> The copy-paste was done by a student (I thought that the it was part of the github repository - sorry if it was not)

MIT != public domain. It still requires attribution. Even if you were under the assumption that the front-end was all part of the same MIT-licensed repo, I don't understand why none of the publications mention it. After all, it does seem to be a relevant part of your demo. There's a whole section about it in your paper. Aside from some very minor and insignificant modifications you made, pretty much all of what you describe there in terms of the UI was written my me.

> I suppose that the hyperlink in the repository confused our student: it points to your web site and probably he supposed that is is the same thing as the code in the repository, while it was not.

Hmm, I doubt this is what happened. The `displacy-ent` repo includes a fully functional front-end (which looks pretty different, actually). If you [go back in the history](https://github.com/uhh-lt/targer/tree/49696dfd705003b5a30e0fe70bf1b4f1d6b2e0ee/frontend/frontend-displacy) of this repo here, you'll see that the components of this front-end were initially used. For some reason, it was then changed to the one I built specifically for our website. 

Doing this required quite a bit of effort: downloading the code and assets by digging through the source, putting them together again, unminifying the CSS, removing our logo and everything else referencing us/our website. That's typically not how you "use" open-source software.

> Please let me know if this is ok.

I appreciate the gesture, but this is incorrect. Your front-end isn't based on the MIT-licensed `displacy-ent`. It *also* uses a script from that repo, yes (presumably because it was too tricky to also copy-paste the minified Vue code from our website). But fundamentally, your front-end is a copy-paste of a page from our website that's not available under any license. So I'd appreciate it if you could just take it down.

**Comment by honnibal** [comment]
>  the front end was an important part but we just decided to take something decent from open source as none of us is a specialist in the front end

Sure, except that's not what you say in your paper. From the introduction:

> In this paper, we close this gap by  introducing TARGER:  a  system  with  a  user-friendly web interface...TARGER’s web interface and API also allow for very fast keyword-based argumentretrieval from a pre-tagged version of the CommonCrawl-based DepCC (Panchenko et al., 2018).

You elaborate on the web UI's functionality in some detail in Section 3.4:

> The web interface of TARGER offers two functionalities: Analyze Text and Search Arguments.   On the analysis tab (cf. Figure 2), the user can choose one of the deployed models to identify arguments in a user-provided free text.  The result is shown with colored labels for different types of argumentative units (premises and claims) as well as detected  named  entities  (nested  tags  for  entities  in argumentative units are supported).  Once a result is  shown,  it  is  possible  to  customize  the  display by enabling/disabling different labels without per-forming additional tagging runs.

> On  the  retrieval  tab  (cf.  Figure  3),  the  user can enter a keyword query and choose whether it should be matched in claims, premises, etc. Every retrieved result is rendered as a text fragment colorized with argument and entity information just as on the analysis tab.  To enable provenance, the URL of the source document is also provided.

Pretty much all of the features you're elaborating here come from Ines's work --- but because you do not attribute them, they are presented as your own contributions. The web UI is also mentioned more generally as a contribution in the conclusion:

>  With the available RESTful API and the web interface, we  make  the  recent  argument  mining  technologies more accessible and usable to researchers and developers  as  well  as  the  general  public.

On your poster under "Targer's assets", the first bullet point reads:

> Easily accessible web interface and RESTful API.

Would you agree that your paper presents the web UI as one of the contributions of the paper? And if so, could you explain why you decided not to explain that the web UI was simply "taking something decent from open-source"? Were you worried that if you included a link to [our demo](https://explosion.ai/demos/displacy-ent) as the source of your front-end, the paper would be less likely to get accepted?

**Comment by alexanderpanchenko** [comment]
Hello, @ines and @honnibal. 

Please do not take me wrong: I do not say that there was an error from our side. There was indeed a very wrong thing to do from the side of a bachelor student who implemented the front-end. We overlooked it (partially because of a bit misleading URL) in the header of the repository (but again it is not an excuse, I just try to reconstruct what happened). 

I personally did not actually participate in the coding of this project, as you can observe from commits in the repository. Of course, I would personally never do it neither ask somebody to do it. It would be a really mad and wrong thing to do. 

We will rework the repository removing all wrongly adapted HTML and other UI elements. I personally was indeed under impression that the UI part is coming from the MIT licensed repository as most of the authors in our team. 

**Please let us know any kind of actions you would like us to perform. We will try to implement what you ask.**

If you give us some time to remove letting us run the current version until this change is done.  Anyways, I am waiting for your comments and please be assured that we are really sorry about this incident.

**Comment by honnibal** [comment]
You were involved in writing the paper though, right? And you were aware that the front-end wasn't being attributed in the paper, poster presentation or website. Could you comment on why you made that decision?

**Comment by alexanderpanchenko** [comment]
This is right, I was involved in writing. I agree that we should have mentioned also in the paper the displacy-ent. It was mentioned, I think somewhere in the repository, but not prominent enough: not proportional to its importance in the project. 

It was however not a concious decision made because of some bad intent. It was a very stupid overlooked thing. 

PS. It is really pity that you did not speak to us during the poster session and we are discussing it here. I will be happy to speak with you tomorrow or in any other day. May be it will be more convinient and easy to explain. I really hope for your understanding!

**Comment by alexteua** [comment]
Dear @ines , 

maybe there is a misunderstanding.

> I appreciate the gesture, but this is incorrect. Your front-end isn't based on the MIT-licensed displacy-ent.

We don't mean that is it like that in the current state. Besides to the mention Alexander made in the main README, we ALSO will replace everything we just discussed above. We will appreciate, if until then we can keep the current demo.

**Comment by honnibal** [comment]
>  It is really pity that you did not speak to us during the poster session and we are discussing it here.

We're not at ACL unfortunately. Participating in an academic conference when you're self-employed is actually quite a commitment: the conferences are very expensive, and they last quite a long time.

**Comment by alexanderpanchenko** [comment]
@honnibal Ok. Sorry, you described precisely our poster. That was the reason why I decided you are around as we did not publish it anywhere.

**Comment by honnibal** [comment]
Ah, sorry for the confusion. We first saw the demo after a friend sent us a photo of the poster.

**Comment by alexanderpanchenko** [comment]
Just let me make it cristal clear once again: we did not want to intentionally copy private UI elements of one of the most visible NLP company on the market and tell everybody that it is our work hoping to capitalize on it. Rather we were under an impression that there was an MIT project which fits well our needs (visualizing of span annotation) and we can use it. We should have mentioned in the paper the original UI GitHub repository. We will work on REMOVING all explosion.ai non-MIT work. I hope for your understanding of the fact that no bad intentions were in our minds.

**Comment by ines** [comment]
Thanks for the clarification. I understand that once the site was copied, you weren't aware that the code in your repo wasn't the code from our MIT-licensed open-source tool. After all, your demo looks and works pretty much exactly like our demo linked from that repo. So I can definitely see where that impression came from.

The real problem here is that your demo paper fails to acknowledge that one of the main components of your demo wasn't actually created by you at all. Instead, as @honnibal stated above, it consistently implies that *my* work, open-source or not, was *your* contribution. I personally find it very frustrating to accept that the missing attribution was merely an oversight.

> We don't mean that it is like that in the current state. Besides to the mention Alexander made in the main README, we ALSO will replace everything we just discussed above.

Sure, if you choose to use my MIT-licensed code in the future, then an attribution like that is okay. Attributions don't have to be glowing "thank you" notes like this btw. A footnote is totally fine, just like you'd do citations in a paper.

**Comment by alexanderpanchenko** [comment]
Hello @ines,

I am going to write to ACL publication chairs to let us update the current version of the paper - I hope it is technically possible but will most likely take a long time to update. Besides, I will update our ArXiv paper with the proper acknowledgments today. I will attach here the updated paper version so that you can let me know if the wordings are ok or not. 

Once we re-worked the UI (it may take some time as none of us really expert in UI - this was the reason in the first time to use your repository) we will also update the screenshots in the paper. 

Best,
Alex.

**Comment by alexanderpanchenko** [comment]
I included these additions to the paper: 

<img width="296" alt="image" src="https://user-images.githubusercontent.com/1456830/62133918-efac2c00-b2df-11e9-9a43-0cf41797bc2d.png">


<img width="540" alt="image" src="https://user-images.githubusercontent.com/1456830/62133620-5da42380-b2df-11e9-9ebb-ac38c4a0f0e0.png">

@ines please let me know if anything shall be added to these acknowledgements. I've just pushed the updated version to ArXiv. It should be available soon.

**Comment by alexanderpanchenko** [comment]
Updated PDF is available at https://www.inf.uni-hamburg.de/en/inst/ab/lt/publications/2019-chernodubetal-acl19demo-targer.pdf and also I asked update the PDF on the web site of webis. Upon your reply I can also ask to update this to ACL anothlogy.

**Comment by ines** [comment]
This looks good to me. Thanks for moving quickly on this 🙂 

Once you've replaced the front-end in the demo, feel free to close this issue.

**Comment by alexanderpanchenko** [comment]
Dear Ines, 

I also requested now publication chairs of ACL to update the PDF in the ACL Anthology with the mentioned above PDF - I hope they let us do so. Besides, we discussed today with @alexteua the plan to implement the required changes. A week may be needed (hopefully not more) to do it due to the fact that the core developer currently has exams (and I personally did not work with front-end technology for 5+ years and can't implement it right now myself). I am sorry for this delay but we make our best to deliver it as soon as possible and close this issue. 

Best,
Alex.

**Comment by alexanderpanchenko** [comment]
Just a small update: I got a response from ACL 2019 publication chairs. They were not able to update the paper. However, I contacted Director of ACL and he suggested to use the formal request for a revision (post proceeding). It shall be processed, but I am not sure when exactly. I hope it will be done sooner than later. Here is the issue: 
https://github.com/acl-org/acl-anthology/issues/490

**Comment by alexanderpanchenko** [comment]
I am closing this issue as:

1) We redesigned and deployed the new front end: http://ltdemos.informatik.uni-hamburg.de/targer/#

2) I've submitted correction to ACL Anthology so that the final paper will looks like this: http://panchenko.me/slides/TARGER.pdf

3) We've updated the preprints where possible ourselves to the version which contains the missed acknowledgements.
